spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/ssm?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      max-wait: 60000
  redis:
    host: localhost
    port: 6379
    database: 0

pagehelper:
  reasonable: true
  defaultCount: true # 分页插件默认参数支持 default-count 形式，自定义扩展的参数，必须大小写一致
  helperDialect: mysql
mybatis:
  mapper-locations: classpath:/mapper/*.xml